### ISSUE TITLE
TypeScript samples

### ISSUE THREAD

**Issue by VPKSoft** [tryphotino/photino.Samples#35]
Hi,
Is there a plan to create TypeScript samples for Photino? Or if anyone has created a React TypeScript sample I would much appreciate a link to the source code 🙂

**Comment by philippjbauer** [comment]
There is no plan to create TypeScript samples for Photino since it is independent of the technology that is used for the web application that is served.

You can start a new React project with TS enabled by doing the following from within the `Photino.HelloPhotino.React` folder:

```
rm -rf UserInterface
npx create-react-app your-project-name --template typescript
mv your-project-name UserInterface
```

Then configure your new React app to compile into the `wwwroot` (for file-system access) or `Resources/wwwroot` (if you want to embed your files into the application) folder:

```
{
    "scripts": {
        ...
        "build": "BUILD_PATH='../wwwroot' react-scripts build",
        ...
    },
}
```

**Comment by VPKSoft** [comment]
Hi,
Thanks for the help to the right direction 👍 I modified the sample to TypeScript with hooks if someone else is interested: https://github.com/VPKSoft/photino.Samples/tree/master/Photino.HelloPhotino.React.
